// Package engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package engine

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PostRecommendTradesJSONBodyAggressiveness.
const (
	Aggressive   PostRecommendTradesJSONBodyAggressiveness = "aggressive"
	Conservative PostRecommendTradesJSONBodyAggressiveness = "conservative"
	Neutral      PostRecommendTradesJSONBodyAggressiveness = "neutral"
)

// FaSuggestion defines model for FaSuggestion.
type FaSuggestion struct {
	DeltaValue    float32 `json:"delta_value"`
	PlayerId      string  `json:"player_id"`
	Rationale     *string `json:"rationale,omitempty"`
	SuggestedFaab *int    `json:"suggested_faab,omitempty"`
}

// LeagueIngest defines model for LeagueIngest.
type LeagueIngest struct {
	Rosters []Roster `json:"rosters"`

	// Settings scoring_json, roster_rules_json, faab, budget, etc.
	Settings map[string]interface{} `json:"settings"`
	Teams    []Team                 `json:"teams"`
}

// Roster defines model for Roster.
type Roster struct {
	PlayerId string `json:"player_id"`

	// Slot QB/RB/WR/TE/FLEX/BN/IR
	Slot   string `json:"slot"`
	TeamId string `json:"team_id"`
}

// Team defines model for Team.
type Team struct {
	Id      string  `json:"id"`
	Manager *string `json:"manager,omitempty"`
	Name    string  `json:"name"`
}

// TradeSuggestion defines model for TradeSuggestion.
type TradeSuggestion struct {
	DeltaThem      float32  `json:"delta_them"`
	DeltaYou       float32  `json:"delta_you"`
	Get            []string `json:"get"`
	Give           []string `json:"give"`
	OpponentTeamId string   `json:"opponent_team_id"`
	Rationale      *string  `json:"rationale,omitempty"`
}

// PostComputeValuationsJSONBody defines parameters for PostComputeValuations.
type PostComputeValuationsJSONBody struct {
	// Source projection source id
	Source *string `json:"source,omitempty"`
	Week   *int    `json:"week,omitempty"`
}

// GetRecommendFreeAgentsParams defines parameters for GetRecommendFreeAgents.
type GetRecommendFreeAgentsParams struct {
	TeamId string `form:"team_id" json:"team_id"`
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostRecommendTradesJSONBody defines parameters for PostRecommendTrades.
type PostRecommendTradesJSONBody struct {
	Aggressiveness       *PostRecommendTradesJSONBodyAggressiveness `json:"aggressiveness,omitempty"`
	MaxOffersPerOpponent *int                                       `json:"max_offers_per_opponent,omitempty"`
	TeamId               string                                     `json:"team_id"`
}

// PostRecommendTradesJSONBodyAggressiveness defines parameters for PostRecommendTrades.
type PostRecommendTradesJSONBodyAggressiveness string

// PostComputeValuationsJSONRequestBody defines body for PostComputeValuations for application/json ContentType.
type PostComputeValuationsJSONRequestBody PostComputeValuationsJSONBody

// PostIngestLeagueJSONRequestBody defines body for PostIngestLeague for application/json ContentType.
type PostIngestLeagueJSONRequestBody = LeagueIngest

// PostRecommendTradesJSONRequestBody defines body for PostRecommendTrades for application/json ContentType.
type PostRecommendTradesJSONRequestBody PostRecommendTradesJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostComputeValuationsWithBody request with any body
	PostComputeValuationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostComputeValuations(ctx context.Context, body PostComputeValuationsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostIngestLeagueWithBody request with any body
	PostIngestLeagueWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostIngestLeague(ctx context.Context, body PostIngestLeagueJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRecommendFreeAgents request
	GetRecommendFreeAgents(ctx context.Context, params *GetRecommendFreeAgentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRecommendTradesWithBody request with any body
	PostRecommendTradesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRecommendTrades(ctx context.Context, body PostRecommendTradesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostComputeValuationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostComputeValuationsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostComputeValuations(ctx context.Context, body PostComputeValuationsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostComputeValuationsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIngestLeagueWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIngestLeagueRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIngestLeague(ctx context.Context, body PostIngestLeagueJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIngestLeagueRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRecommendFreeAgents(ctx context.Context, params *GetRecommendFreeAgentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecommendFreeAgentsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRecommendTradesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRecommendTradesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRecommendTrades(ctx context.Context, body PostRecommendTradesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRecommendTradesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostComputeValuationsRequest calls the generic PostComputeValuations builder with application/json body
func NewPostComputeValuationsRequest(server string, body PostComputeValuationsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostComputeValuationsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostComputeValuationsRequestWithBody generates requests for PostComputeValuations with any type of body
func NewPostComputeValuationsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/compute/valuations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostIngestLeagueRequest calls the generic PostIngestLeague builder with application/json body
func NewPostIngestLeagueRequest(server string, body PostIngestLeagueJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostIngestLeagueRequestWithBody(server, "application/json", bodyReader)
}

// NewPostIngestLeagueRequestWithBody generates requests for PostIngestLeague with any type of body
func NewPostIngestLeagueRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ingest/league")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRecommendFreeAgentsRequest generates requests for GetRecommendFreeAgents
func NewGetRecommendFreeAgentsRequest(server string, params *GetRecommendFreeAgentsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recommend/free-agents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "team_id", runtime.ParamLocationQuery, params.TeamId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostRecommendTradesRequest calls the generic PostRecommendTrades builder with application/json body
func NewPostRecommendTradesRequest(server string, body PostRecommendTradesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRecommendTradesRequestWithBody(server, "application/json", bodyReader)
}

// NewPostRecommendTradesRequestWithBody generates requests for PostRecommendTrades with any type of body
func NewPostRecommendTradesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recommend/trades")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostComputeValuationsWithBodyWithResponse request with any body
	PostComputeValuationsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostComputeValuationsResponse, error)

	PostComputeValuationsWithResponse(ctx context.Context, body PostComputeValuationsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostComputeValuationsResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// PostIngestLeagueWithBodyWithResponse request with any body
	PostIngestLeagueWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIngestLeagueResponse, error)

	PostIngestLeagueWithResponse(ctx context.Context, body PostIngestLeagueJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIngestLeagueResponse, error)

	// GetRecommendFreeAgentsWithResponse request
	GetRecommendFreeAgentsWithResponse(ctx context.Context, params *GetRecommendFreeAgentsParams, reqEditors ...RequestEditorFn) (*GetRecommendFreeAgentsResponse, error)

	// PostRecommendTradesWithBodyWithResponse request with any body
	PostRecommendTradesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRecommendTradesResponse, error)

	PostRecommendTradesWithResponse(ctx context.Context, body PostRecommendTradesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRecommendTradesResponse, error)
}

type PostComputeValuationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostComputeValuationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostComputeValuationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok *bool `json:"ok,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostIngestLeagueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostIngestLeagueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostIngestLeagueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRecommendFreeAgentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]FaSuggestion
}

// Status returns HTTPResponse.Status
func (r GetRecommendFreeAgentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecommendFreeAgentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostRecommendTradesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TradeSuggestion
}

// Status returns HTTPResponse.Status
func (r PostRecommendTradesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRecommendTradesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostComputeValuationsWithBodyWithResponse request with arbitrary body returning *PostComputeValuationsResponse
func (c *ClientWithResponses) PostComputeValuationsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostComputeValuationsResponse, error) {
	rsp, err := c.PostComputeValuationsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostComputeValuationsResponse(rsp)
}

func (c *ClientWithResponses) PostComputeValuationsWithResponse(ctx context.Context, body PostComputeValuationsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostComputeValuationsResponse, error) {
	rsp, err := c.PostComputeValuations(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostComputeValuationsResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// PostIngestLeagueWithBodyWithResponse request with arbitrary body returning *PostIngestLeagueResponse
func (c *ClientWithResponses) PostIngestLeagueWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIngestLeagueResponse, error) {
	rsp, err := c.PostIngestLeagueWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIngestLeagueResponse(rsp)
}

func (c *ClientWithResponses) PostIngestLeagueWithResponse(ctx context.Context, body PostIngestLeagueJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIngestLeagueResponse, error) {
	rsp, err := c.PostIngestLeague(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIngestLeagueResponse(rsp)
}

// GetRecommendFreeAgentsWithResponse request returning *GetRecommendFreeAgentsResponse
func (c *ClientWithResponses) GetRecommendFreeAgentsWithResponse(ctx context.Context, params *GetRecommendFreeAgentsParams, reqEditors ...RequestEditorFn) (*GetRecommendFreeAgentsResponse, error) {
	rsp, err := c.GetRecommendFreeAgents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecommendFreeAgentsResponse(rsp)
}

// PostRecommendTradesWithBodyWithResponse request with arbitrary body returning *PostRecommendTradesResponse
func (c *ClientWithResponses) PostRecommendTradesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRecommendTradesResponse, error) {
	rsp, err := c.PostRecommendTradesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRecommendTradesResponse(rsp)
}

func (c *ClientWithResponses) PostRecommendTradesWithResponse(ctx context.Context, body PostRecommendTradesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRecommendTradesResponse, error) {
	rsp, err := c.PostRecommendTrades(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRecommendTradesResponse(rsp)
}

// ParsePostComputeValuationsResponse parses an HTTP response from a PostComputeValuationsWithResponse call
func ParsePostComputeValuationsResponse(rsp *http.Response) (*PostComputeValuationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostComputeValuationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok *bool `json:"ok,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostIngestLeagueResponse parses an HTTP response from a PostIngestLeagueWithResponse call
func ParsePostIngestLeagueResponse(rsp *http.Response) (*PostIngestLeagueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostIngestLeagueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetRecommendFreeAgentsResponse parses an HTTP response from a GetRecommendFreeAgentsWithResponse call
func ParseGetRecommendFreeAgentsResponse(rsp *http.Response) (*GetRecommendFreeAgentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecommendFreeAgentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []FaSuggestion
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostRecommendTradesResponse parses an HTTP response from a PostRecommendTradesWithResponse call
func ParsePostRecommendTradesResponse(rsp *http.Response) (*PostRecommendTradesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRecommendTradesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TradeSuggestion
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
